# Generated by Django 3.1.3 on 2025-11-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20251125_0145'),
        ('webapp', '0002_auto_20251128_0957'),
    ]

    operations = [
    ]
