# Generated by Django 3.1.3 on 2025-11-28 00:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_study_time',
        ),
        migrations.CreateModel(
            name='StudyGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_study_time', models.DurationField(default=datetime.timedelta(0))),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'study_group')},
            },
        ),
    ]
