# Generated by Django 3.1.3 on 2025-11-28 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_merge_20251128_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='study_groups', through='webapp.StudyGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_study_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
