# Generated by Django 3.1.3 on 2025-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20251128_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
