# Generated by Django 3.1.3 on 2025-11-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20251128_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
