# Generated by Django 3.1.3 on 2025-12-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
