# Generated by Django 3.1.3 on 2025-12-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
