# Generated by Django 3.1.3 on 2025-12-04 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0009_studygroup_report_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='notice',
            field=models.TextField(blank=True, default='등록된 공지사항이 없습니다.'),
        ),
    ]
